// Simple test preset - just a sine wave
const testPreset = {
	"name": "Test Sine",
	"algorithm": 32, // All operators are carriers
	"feedback": 0,
	"lfoSpeed": 0,
	"lfoDelay": 0,
	"lfoPitchModDepth": 0,
	"lfoAmpModDepth": 0,
	"lfoPitchModSens": 3,
	"lfoWaveform": 0,
	"lfoSync": 0,
	"pitchEnvelope": {
		"rates": [0, 0, 0, 0],
		"levels": [50, 50, 50, 50]
	},
	"controllerModVal": 0,
	"aftertouchEnabled": 0,
	"fbRatio": 0,
	"operators": [
		{
			"idx": 0,
			"enabled": true,
			"rates": [99, 0, 0, 70],
			"levels": [99, 99, 99, 0],
			"detune": 0,
			"velocitySens": 0,
			"lfoAmpModSens": 0,
			"volume": 99,
			"oscMode": 0,
			"freqCoarse": 1,
			"freqFine": 0,
			"freqRatio": 1,
			"pan": 0,
			"outputLevel": 5.0,
			"ampL": 1,
			"ampR": 1
		},
		{
			"idx": 1,
			"enabled": false,
			"rates": [99, 0, 0, 70],
			"levels": [99, 99, 99, 0],
			"detune": 0,
			"velocitySens": 0,
			"lfoAmpModSens": 0,
			"volume": 0,
			"oscMode": 0,
			"freqCoarse": 1,
			"freqFine": 0,
			"freqRatio": 1,
			"pan": 0,
			"outputLevel": 0,
			"ampL": 1,
			"ampR": 1
		},
		{
			"idx": 2,
			"enabled": false,
			"rates": [99, 0, 0, 70],
			"levels": [99, 99, 99, 0],
			"detune": 0,
			"velocitySens": 0,
			"lfoAmpModSens": 0,
			"volume": 0,
			"oscMode": 0,
			"freqCoarse": 1,
			"freqFine": 0,
			"freqRatio": 1,
			"pan": 0,
			"outputLevel": 0,
			"ampL": 1,
			"ampR": 1
		},
		{
			"idx": 3,
			"enabled": false,
			"rates": [99, 0, 0, 70],
			"levels": [99, 99, 99, 0],
			"detune": 0,
			"velocitySens": 0,
			"lfoAmpModSens": 0,
			"volume": 0,
			"oscMode": 0,
			"freqCoarse": 1,
			"freqFine": 0,
			"freqRatio": 1,
			"pan": 0,
			"outputLevel": 0,
			"ampL": 1,
			"ampR": 1
		},
		{
			"idx": 4,
			"enabled": false,
			"rates": [99, 0, 0, 70],
			"levels": [99, 99, 99, 0],
			"detune": 0,
			"velocitySens": 0,
			"lfoAmpModSens": 0,
			"volume": 0,
			"oscMode": 0,
			"freqCoarse": 1,
			"freqFine": 0,
			"freqRatio": 1,
			"pan": 0,
			"outputLevel": 0,
			"ampL": 1,
			"ampR": 1
		},
		{
			"idx": 5,
			"enabled": false,
			"rates": [99, 0, 0, 70],
			"levels": [99, 99, 99, 0],
			"detune": 0,
			"velocitySens": 0,
			"lfoAmpModSens": 0,
			"volume": 0,
			"oscMode": 0,
			"freqCoarse": 1,
			"freqFine": 0,
			"freqRatio": 1,
			"pan": 0,
			"outputLevel": 0,
			"ampL": 1,
			"ampR": 1
		}
	]
};

export default testPreset;